config/routes.rb
GridviewDemoStore::Application.routes.draw do
  
  match ":controller/:action.:format"
  resources :announcements

  resources :products

   root :to => 'products#index'

end

app/models/announcement.rb
class Announcement < ActiveRecord::Base
  attr_accessible :ends_at, :message, :starts_at

  def self.current_announcements(hide_time)
    #with_scope :find => { :conditions => "starts_at <= 'now' AND ends_at >= 'now'" } do
      if hide_time.nil?
        Announcement.find(:all)
      else
        Announcement.find(:all, :conditions => ["updated_at > ? OR starts_at > ?", hide_time, hide_time])
      end
    #end
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :name, :price
end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  # GET /announcements
  # GET /announcements.json
  def index
    @announcements = Announcement.all

    respond_to do |format|
      format.html # index.html.erb
      format.js
      format.json { render json: @announcements }
    end
  end

  # GET /announcements/1
  # GET /announcements/1.json
  def show
    @announcement = Announcement.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.js
      format.json { render json: @announcement }
    end
  end

  # GET /announcements/new
  # GET /announcements/new.json
  def new
    @announcement = Announcement.new

    respond_to do |format|
      format.html # new.html.erb
      format.js
      format.json { render json: @announcement }
    end
  end

  # GET /announcements/1/edit
  def edit
    @announcement = Announcement.find(params[:id])
  end

  # POST /announcements
  # POST /announcements.json
  def create
    @announcement = Announcement.new(params[:announcement])

    respond_to do |format|
      if @announcement.save
        format.html { redirect_to @announcement, notice: 'Announcement was successfully created.' }
        format.json { render json: @announcement, status: :created, location: @announcement }
      else
        format.html { render action: "new" }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /announcements/1
  # PUT /announcements/1.json
  def update
    @announcement = Announcement.find(params[:id])

    respond_to do |format|
      if @announcement.update_attributes(params[:announcement])
        format.html { redirect_to @announcement, notice: 'Announcement was successfully updated.' }
        format.js
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.js
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /announcements/1
  # DELETE /announcements/1.json
  def destroy
    @announcement = Announcement.find(params[:id])
    @announcement.destroy

    respond_to do |format|
      format.html { redirect_to announcements_url }
      format.json { head :no_content }
      format.js
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/javascripts_controller.rb
class JavascriptsController < ApplicationController
	
	def hide_announcement
		session[:announcement_hide_time] = Time.now
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

	def clippy(text, bgcolor='#FFFFFF')
		  html = <<-EOF
		  <object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000"
		        width="10"
		        height="14"
		        id="clippy" >
		<param name="movie" value="/clippy.swf"/>
		<param name="allowScriptAccess" value="always" />
		<param name="quality" value="high" />
		<param name="scale" value="noscale" />
		<param NAME="FlashVars" value="text=#{text}">
		<param name="bgcolor" value="#{bgcolor}">
		<embed src="/clippy.swf"
		       width="110"
		       height="14"
		       name="clippy"
		       quality="high"
		       allowScriptAccess="always"
		       type="application/x-shockwave-flash"
		       pluginspage="http://www.macromedia.com/go/getflashplayer"
		       FlashVars="text=#{text}"
		       bgcolor="#{bgcolor}"
		/>
		</object>
		 EOF
		 raw(html)
	end

	def current_announcements
	  @current_announcements ||= Announcement.current_announcements(session[:announcement_hide_time])
	end
end

app/helpers/javascripts_helper.rb
module JavascriptsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/announcements/_form.html.erb
<%= form_for(@announcement) do |f| %>
  <% if @announcement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@announcement.errors.count, "error") %> prohibited this announcement from being saved:</h2>

      <ul>
      <% @announcement.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_area :message %>
  </div>
  <div class="field">
    <%= f.label :starts_at %><br />
    <%= f.datetime_select :starts_at %>
  </div>
  <div class="field">
    <%= f.label :ends_at %><br />
    <%= f.datetime_select :ends_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/announcements/edit.html.erb
<h1>Editing announcement</h1>

<%= render 'form' %>

<%= link_to 'Show', @announcement %> |
<%= link_to 'Back', announcements_path %>

app/views/announcements/index.html.erb
<h1>Listing announcements</h1>

<table>
  <tr>
    <th>Message</th>
    <th>Starts at</th>
    <th>Ends at</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @announcements.each do |announcement| %>
  <tr>
    <td><%= announcement.message %></td>
    <td><%= announcement.starts_at %></td>
    <td><%= announcement.ends_at %></td>
    <td><%= link_to 'Show', announcement %></td>
    <td><%= link_to 'Edit', edit_announcement_path(announcement) %></td>
    <td><%= link_to 'Destroy', announcement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Announcement', new_announcement_path %>

app/views/announcements/new.html.erb
<h1>New announcement</h1>

<%= render 'form' %>

<%= link_to 'Back', announcements_path %>

app/views/announcements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Message:</b>
  <%= @announcement.message %>
</p>

<p>
  <b>Starts at:</b>
  <%= @announcement.starts_at %>
</p>

<p>
  <b>Ends at:</b>
  <%= @announcement.ends_at %>
</p>


<%= link_to 'Edit', edit_announcement_path(@announcement) %> |
<%= link_to 'Back', announcements_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GridviewDemoStore</title>
  <!-- [if 1t IE 9]>
  	<script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]"-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag :defaults%>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
	<div class="navbar navbar-fixed-top">
  		<div class="navbar-inner">
    		<div class="container">
	      		<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
	       		 	<span class="icon-bar"></span>
	        		<span class="icon-bar"></span>
	        		<span class="icon-bar"></span>
	      		</a>
	      		<a class="brand" href="#">Gridview Demo store</a>
	      		<div class="nav-collapse">
	        		<ul class="nav">
	          			<li><%= link_to "Browse Products", products_path %></li>
	          			<li><%= link_to "Price List" %></li>
				        <li><%= link_to "Contact Us" %></li>
	   			        <li><%= link_to "Cart" %></li>
	        		 </ul>
	      		</div>
    		</div>
  		</div>
	</div>
	<% unless current_announcements.empty? %>
		<div id="announcement">
		  <% for announcement in current_announcements %>
		    <p><!--%=h announcement.message %--></p>
		  <% end %>
		  <p><!--%= link_to "Hide this message", :url => "/controllers/hide_announcement.js.rjs", :remote => true %--></p>
		</div>
    <% end %>
	<div class="container">
		<div class= "row">
			<div class="span10"><%= yield %></div>
			<div class="span2">

				<h2>About Us</h2>
				<textarea id="paste-text" class="empty" placeholder="Test your paste here" ></textarea>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
			</div>
		</div>
	</div>
</body>
</html>

app/views/products/_form.html.erb
<%= form_for @product, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :price, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :price, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                products_path, :class => 'btn' %>
  </div>
<% end %>

app/views/products/edit.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/products/index.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:price) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <% if product.id.even? 
              bgcolor="#FFFFFF"              
            else
              bgcolor="#F9F9F9"
            end %>
        <td><%= link_to product.id, product_path(product) %></td>
        <td><%= product.name %><br /><%= clippy( product.name, bgcolor) %></td>
        <td><%= product.price %></td>
        <td><%=l product.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_product_path(product), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      product_path(product),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
            <%= clippy( "Product Name:"+product.name+" price:"+product.price.to_s, bgcolor) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_product_path,
            :class => 'btn btn-primary' %>

app/views/products/new.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/products/show.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @product.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:price) %>:</strong></dt>
  <dd><%= @product.price %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              products_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_product_path(@product), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              product_path(@product),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>